### ISSUE TITLE
The server is running, but fails to accept the SSH connection.

### ISSUE THREAD

**Issue by yeisonvargasf** [niiknow/vestacp#1]
**Command**

`ssh -p 2222 -v admin@0.0.0.0`

**Debug info**

`OpenSSH_7.3p1, LibreSSL 2.4.1
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 20: Applying options for *
debug1: Connecting to 0.0.0.0 [0.0.0.0] port 2222.
debug1: Connection established.
debug1: identity file /Users/[user]/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/[user]/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/[user]/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/[user]/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/[user]/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/[user]/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/[user]/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/[user]/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.3
ssh_exchange_identification: Connection closed by remote host`

**OS**
`Mac OS X Sierra`

**Docker Version**
`1.12.5`

**Comment by noogen** [comment]
Where are you getting this error?   I'm guessing it's coming from your Mac and not from server log?  Unfortunately, I've been messing around with sshd so I might have broken something.  Also, I have only tested ssh with login and password.

Also, most configuration I've seen on docker-machine Mac OS X for IP  is 192.168.99.x.  How are you binding to 0.0.0.0?

Password authentication is still enabled so you will have to enter password even with ssh key.
```
PasswordAuthentication yes
```

Current version 0.8.6 works fine with ssh key.  **You will need to upload your id_rsa.pub into /home/admin/.ssh/authorized_keys - https://www.digitalocean.com/community/tutorials/initial-server-setup-with-ubuntu-16-04**
```
$ ssh -v admin@xxx.xxx.xxx -p 2222
OpenSSH_7.1p2, OpenSSL 1.0.2h  3 May 2016
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Connecting to xxx.xxx.xxx [xxx.xxx.xxx.xxx] port 2222.
debug1: Connection established.
debug1: identity file /c/Users/tom/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /c/Users/tom/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /c/Users/tom/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /c/Users/tom/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /c/Users/tom/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /c/Users/tom/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /c/Users/tom/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /c/Users/tom/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubunt                u-4ubuntu2.1
debug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.1 pat OpenSSH* compat 0x04000000
debug1: Authenticating to xxx.xxx.xxx:2222 as 'admin'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client chacha20-poly1305@openssh.com <implicit> none
debug1: kex: client->server chacha20-poly1305@openssh.com <implicit> none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:agNfOUsL7x+XqusDZDwLaj7R50+G                NaBMZZl/Q8rk6Ec
debug1: Host '[xxx.xxx.xxx]:2222' is known and matches the ECDSA host ke                y.
debug1: Found key in /c/Users/tom/.ssh/known_hosts:7
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /c/Users/tom/.ssh/id_rsa
debug1: Authentications that can continue: publickey,password
debug1: Trying private key: /c/Users/tom/.ssh/id_dsa
debug1: Trying private key: /c/Users/tom/.ssh/id_ecdsa
debug1: Trying private key: /c/Users/tom/.ssh/id_ed25519
debug1: Next authentication method: password
admin@xxx.xxx.xxx's password:
debug1: Authentications that can continue: publickey,password
Permission denied, please try again.
admin@xxx.xxx.xxx's password:
debug1: Authentication succeeded (password).
Authenticated to xxx.xxx.xxx([xxx.xxx.xxx.xxx]:2222).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-59-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
Last login: Wed Jan 25 04:24:44 2017 from xxx.xxx.xxx.xxx
admin@dreamfactory-vestacp-1:~$ exit
logout
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
debug1: channel 0: free: client-session, nchannels 1
Connection to xxx.xxx.xxx closed.
Transferred: sent 3276, received 3228 bytes, in 18.8 seconds
Bytes per second: sent 174.7, received 172.1
debug1: Exit status 0
```

I'll work on redirecting the ssh config folder next so you can persist/updated the configuration to support ssh key and disable PasswordAuthentication.

Please wait for version > 0.8.6

For now, login without sshkey with: ssh admin@0.0.0.0 -p 2222
use password: MakeItSo17

**Comment by noogen** [comment]
@yeisonvargasf please check that you're using the correct IP.

You can try/checkout the demo here:  https://cloud2.noogen.net:8083/
Login/pass: admin/MakeItSo17

ssh admin@cloud2.noogen.net -p 2222

I've redirect ssh and updated image to version 0.8.7

**Comment by noogen** [comment]
Closing ticket.  Please feel free to re-open and provide details if there is still an issue.

FYI - latest version (0.8.19) should be pretty complete and stable.  I have switched most of my Production setup out with it.
