### ISSUE TITLE
template memory limit

### ISSUE THREAD

**Issue by patsotoe** [niiknow/vestacp#103]
Hi how i can edit the templates for the sites, i need increase the memory limit.

**Comment by noogen** [comment]
What template are you using (php-fpm or php-fcgi) and what settings are you trying to set?  If you're using php-fpm, then simply create a `.user.ini` file in public_html directory with the following:

Default is 128M so you can increase to 512M like so.
```
memory_limit=512M
```

If it's php-fcgi then simply create an `.htaccess` file.

**Comment by noogen** [comment]
Also remember, you can simply change any nginx config by adding a conf file under the website private directory `/home/{user}/web/{website}/private/{filename}.conf` , if nginx fastcgi config is what you're after.
