### ISSUE TITLE
Backup Failed Until Disk Full

### ISSUE THREAD

**Issue by LenKiMo** [niiknow/vestacp#105]
I met an backup problem that auto backup failed, and cause retry every 5 minutes, and finally result in disk full with `tmp.*` folder.

The log shows that problem occurs when backup database:
```
-- DB --
2019-10-13 02:31:00 admin_default (mysql)
2019-10-13 02:31:00 admin_db (pgsql)
Error: Connection to localhost failed
```

At first I might think it's password problem, then I check the files
```
/usr/local/vesta/conf/mysql.conf
/vesta/root/.my.cnf
```
to insure they filled the same, correct password.

Then I checked that Postgresql and Mysql is running normally, at least Vesta doesn't give any warning.
Though PHPMyAdmin and PHPPgAdmin are not running at this time.

Can you give me any advice about what should I check or try next?

**Comment by noogen** [comment]
This is a common issue in Vesta.  Those databases (admin_default, admin_db) are created by Vesta.  If you're not using those databases, which is the common case ref (https://forum.vestacp.com/viewtopic.php?t=13629), please delete them, hint - you can use the VestaCP Database tab to do that.  Look at error log files for details `/usr/local/vesta/log/error.log` and `/usr/local/vesta/log/db.log` 

Example issues:

https://github.com/serghey-rodin/vesta/issues?utf8=%E2%9C%93&q=is%3Aissue+backup+fail
https://github.com/serghey-rodin/vesta/issues/913
https://github.com/serghey-rodin/vesta/issues/1167
https://github.com/serghey-rodin/vesta/issues/1478

**Comment by LenKiMo** [comment]
It works, now the backup can ending correctly.
Thanks for your information, it helps me a lot.
