### ISSUE TITLE
adminer

### ISSUE THREAD

**Issue by patsotoe** [niiknow/vestacp#109]
Hi friend i´m trying to import a mysql database in adminer, when i do the upload i have the following error i thought  i need increase the memory and time for adminer where i can do this?

Thank
![Anotación 2019-10-20 223523](https://user-images.githubusercontent.com/46969064/67170701-f6e85080-f389-11e9-8b43-15e168c61d4c.png)

**Comment by noogen** [comment]
To increase memory, you can probably add .user.ini to `/usr/share/adminer/public/`

**Comment by patsotoe** [comment]
finally i import the sql from the container in docker.
