### ISSUE TITLE
Integrate SpamAssassin ruleset

### ISSUE THREAD

**Issue by schulluk** [niiknow/vestacp#11]
What do you think about https://github.com/SS88UK/SpamAssassinRules ?
Is it worth to integrate it into the release?

**Comment by noogen** [comment]
I'll look into this in the next release.  In addition, I'll probably also redirect /etc/mail folder so user can self-update the configuration file to their liking.

**Comment by schulluk** [comment]
In merge request #13 I redirected the directories for /etc/mail and /etc/spamassassin.
Now everyone can manage their rules by themselves.

Just use a release which was created after 2017-08-05, 21:25 UTC
