### ISSUE TITLE
ioncube

### ISSUE THREAD

**Issue by patsotoe** [niiknow/vestacp#111]
hi, how we can activate ioncube in vestacp?

**Comment by noogen** [comment]
ioncube is installed for all php version inside of `/usr/lib/php/$date/ioncube*.so` so depend on your php version and what you're using (apache phpfcgi or nginx php-fpm), add specific ini.  For example of php7.3:

apache fcgi
```sh
sudo echo 'zend_extension = "/usr/lib/php/20180731/ioncube_loader_lin_7.3.so"' > /etc/php/7.3/apache2/conf.d/00-ioncube.ini
```

fpm
```sh
sudo echo 'zend_extension = "/usr/lib/php/20180731/ioncube_loader_lin_7.3.so"' > /etc/php/7.3/fpm/conf.d/00-ioncube.ini
```

**Comment by patsotoe** [comment]
thanks for the suggestion, firstly i just found the file ioncube_loader_lin_7.2.so in the following directory  /opt/vestacp/vesta/local/vesta/ioncube/ioncube_loader_lin_7.2.so, so i run the following command as you suggest:

sudo echo 'zend_extension = "/opt/vestacp/vesta/local/vesta/ioncube/ioncube_loader_lin_7.2.so"' > /opt/vestacp/vesta/etc/php/7.2/apache2/conf.d/00-ioncube.ini

i check the php info and is reading the file
 
![imagen](https://user-images.githubusercontent.com/46969064/68152463-7a757600-ff22-11e9-8a8c-583c0ee3e229.png)

but when i check if ioncube is installed it´s doesn´t.

![imagen](https://user-images.githubusercontent.com/46969064/68152623-c9bba680-ff22-11e9-9f95-ef15352c4acd.png)

![imagen](https://user-images.githubusercontent.com/46969064/68152931-5cf4dc00-ff23-11e9-8262-bcd9113784ca.png)

**Comment by noogen** [comment]
You want to use the container directory, not the mounted directory.  Try:
```sh
sudo echo 'zend_extension = "/usr/local/vesta/ioncube/ioncube_loader_lin_7.2.so"' > /opt/vestacp/vesta/etc/php/7.2/apache2/conf.d/00-ioncube.ini
```

**Comment by patsotoe** [comment]
yes thanks for the support, i have to enter to the docker container and run exactly your commands.

I add a docker container restart -yourcontainer- and works.

Thanks again for the help!
