### ISSUE TITLE
Password.txt file not saved properly

### ISSUE THREAD

**Issue by stopspazzing** [niiknow/vestacp#115]
> docker exec $CONTAINER_ID cat /vesta-start/root/password.txt

`cat: /vesta-start/root/password.txt: No such file or directory`

Yes using the correct container. According to code in dockerfile it saves it in a completely different area:

`https://github.com/niiknow/vestacp/blob/ed0424b6295a4fb8dfdec8cddfd971c5eed6a1f2/Dockerfile#L102`

However folder root and admin are void of passwords.txt file.

**Comment by stopspazzing** [comment]
FYI for anyone else, temp solution to fix this is change password:

`sudo docker exec $CONTAINER_ID /usr/local/vesta/bin/v-change-user-password admin YOURNEWPASSWORD
`

**Comment by noogen** [comment]
I wonder what happen.  It works for me on the latest container:

```
docker run -it 97b7efeba1f8 /bin/bash
root@eed4e63fa440:/# cat /vesta-start/root/password.txt
Ohm*******th
root@eed4e63fa440:/# exit
exit
```

But thanks, I've updated the doc with your suggestion.

**Comment by Zippersk** [comment]
I have same problem. There was no `password.txt` anywhere inside the container: 
```
docker exec -it vestacp /bin/bash
root@194269432a2c:/# find . -name passwor*
./var/cache/debconf/passwords.dat
./var/lib/roundcube/plugins/password
./var/lib/pam/password
./etc/roundcube/plugins/password
./usr/lib/postgresql/9.6/lib/passwordcheck.so
./usr/share/roundcube/plugins/password
./usr/share/roundcube/plugins/password/password.php
./usr/share/roundcube/plugins/password/password.js
./usr/share/doc/postgresql-doc-11/html/passwordcheck.html
./usr/local/lib/python3.7/dist-packages/awscli/examples/ec2/wait/password-data-available.rst

```

Executing `v-change-user-password` does not help. I still can't login :/

**Comment by Zippersk** [comment]
There was no error on version `1.9.0`. Password.txt was successfully created here.
