### ISSUE TITLE
auto renew ssl 

### ISSUE THREAD

**Issue by patsotoe** [niiknow/vestacp#117]
Hi i have a problem with the autorenew of the ssl certificate using letsencrypt, this suppose to renew on january 1 of 2020. i have the 1.8.5 version.

**Comment by noogen** [comment]
Is the cron job running for admin user?  I find that, every-time I do an upgrade from one version to another, I have to suspend and unsuspend the cron to make sure it is running.  You can check the container log to see if cron jobs are running https://docs.docker.com/engine/reference/commandline/logs/
