### ISSUE TITLE
Apache2 Start Failed due to Lacks of php7.1.so

### ISSUE THREAD

**Issue by LenKiMo** [niiknow/vestacp#127]
I had run a Vesta docker with an old version, today I remove the old image and container, pull the latest docker build then bind the port and folder.
After install, I found Apache 2 can't start up correctly. By using command manually, it would warning with:

```
sudo service apache2 start
 * Starting Apache httpd web server apache2                                                                                                                                                             *
 * The apache2 configtest failed.
Output of config test was:
apache2: Syntax error on line 70 of /etc/apache2/apache2.conf: Syntax error on line 3 of /etc/apache2/mods-enabled/php7.1.load: Cannot load /usr/lib/apache2/modules/libphp7.1.so into server: /usr/lib/apache2/modules/libphp7.1.so: cannot open shared object file: No such file or directory
Action 'configtest' failed.
The Apache error log may have more information.
```

To locate `/etc/apache2/mods-enabled/` , it has PHP7.1 load but not 7.2, and locate to `usr/lib/apache2/modules/`, it only contains `libphp7.2/3/4.so`.

The server is running PHP 7.2.31 with follow information:
```
PHP 7.2.31-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: May 14 2020 08:27:14) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.31-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.9.6, Copyright (c) 2002-2020, by Derick Rethans

```

And `/etc/apache2/mods-available/php*` only support up to 7.1.

Should I find a copy about `php7.2.load` and put it in manually? Or any other advice?

**Comment by noogen** [comment]
PHP7.1 was end-of-life since December 1, 2019.   Stop using php7.1 and resolve in **1-of-3 ways** below.


1.  Remove php7.1 in mods-enabled.
```
rm /etc/apache2/mods-enabled/php7.1.*
```


2.  Use vesta front-end to backup-restore all users - this is similar to doing server migration.
3.  Or run `bash /bin/vesta-update.sh` - usually required when upgrading from older version of docker image.

**Comment by LenKiMo** [comment]
Fixed, thank you for your information, it saves me.
