### ISSUE TITLE
mydomain.com:5001 to mydomain.com using custom nginx.conf

### ISSUE THREAD

**Issue by gerardvidamo** [niiknow/vestacp#138]
**Issues:**
- dotnet works fine on port 5001 (mydomain.com:5001)
- mydomain.com - 500 Internal Server

**nginx.conf** 
`under /opt/vestacp/home/admin/web/mydomain.com/private`
```
location / {
  # force https-redirects
  if ($scheme = http) {
    return 301 https://$server_name$request_uri;
  }

  proxy_pass          http://0.0.0.0:5001;
  proxy_redirect      off;
  proxy_set_header    Host $host;
  proxy_set_header    X-Real-IP $remote_addr;
  proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for
  proxy_set_header    X-Forwarded-Host $server_name;
}

location /error/ {
  alias   /home/admin/web/mydomain.com/document_errors/;
}

location @fallback {
  proxy_pass      http://0.0.0.0:5001;
}

location ~ /\.ht    {return 404;}
location ~ /\.svn/  {return 404;}
location ~ /\.git/  {return 404;}
location ~ /\.hg/   {return 404;}
location ~ /\.bzr/  {return 404;}
```

**Vesta admin for mydomain.com**
- [x] Proxy Support NGINX
  - Proxy Template: Custom

**Comment by noogen** [comment]
I do the same with self hosted git and don't have a problem.  Check error `logs\site.com.error.log` to see what your 500 error is all about.

Also, I tried your config above and get the following error: `nginx: [emerg] invalid number of arguments in "proxy_set_header" directive in ...` - you're missing a semicolon in `X-Forwarded-For` line.

I run my own self-hosted git and nginx proxy internally.  Here's my working config:
```
location / {
  # force https-redirects
  if ($scheme = http) {
    return 301 https://$server_name$request_uri;
  }

  proxy_pass       http://127.0.0.1:10080;
  proxy_redirect   off;
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header    X-Forwarded-Host $server_name;
}

location /error/ {
   # make sure you change this to valid path
  alias   /home/git/web/git.mydomain.com/document_errors/;
}

location @fallback {
  proxy_pass      http://127.0.0.1:10080;
}

# this should handle all your .period-file and exclude .well-known
# https://github.com/niiknow/vestacp/blob/master/rootfs/etc/nginx/location_optmz_php.conf
include /etc/nginx/location_optmz_php.conf;
```

**Comment by gerardvidamo** [comment]
> Also, I tried your config above and get the following error: `nginx: [emerg] invalid number of arguments in "proxy_set_header" directive in ...` - you're missing a semicolon in `X-Forwarded-For` line.

Sorry typo just for this post, but on my config it should be closed with a semicolon.

> I do the same with self hosted git and don't have a problem. Check error `logs\site.com.error.log` to see what your 500 error is all about.

Errors I found
```
*1 connect() failed (111: Connection refused) while connecting to upstream, client: (myIP), server: mydomain.com, request: "GET / HTTP/1.1", upstream: "http://0.0.0.0:5001/", host: "mydomain.com"
```

I tried your config but still its not accessible on mydomain.com

**Comment by noogen** [comment]
Error said that it cannot access `http://0.0.0.0:5001` upstream.  Are both .net and vesta running in the same docker container?  Otherwise, you can't access with that ip through proxy pass.  Ssh into vestacp container and try `curl http://0.0.0.0:5001` 

If they are two separate containers with the same docker-compose, then use the container name to access it on the same network.

**Comment by gerardvidamo** [comment]
@noogen problem solved!

thanks
