### ISSUE TITLE
phpmyadmin error 404

### ISSUE THREAD

**Issue by uquerx** [niiknow/vestacp#139]
Hello,

When I try to connect on Adminer after to create the DB I got an "404 page no found" error.
The URL who is automatic send is:
myIP/phpmyadmin/ or myIP/phppgadmin/

Instead of Ip I also try to use a domain (ex: mydomain/phpmyadmin) but same issue.

Any idea?
Thanks in advance for your help.
Best regards
xavier

**Comment by noogen** [comment]
See resolution of related issue #88, #102, and #130

**Comment by uquerx** [comment]
Hello Noogen,

Work's fine
Big thanks
