### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by fossxplorer** [niiknow/vestacp#14]
Hi,
awesome, thx for your great work. I'm testing out your image and wonder if you plan to maintain this in the future?
There is a new VestaCP version planned soon :)
@noogen

**Comment by noogen** [comment]
Yes, I am as I am also using it in Production.  I will probably have a new version as soon as a new version of VestaCP come out.  Depend on how everything goes with the upgrade, there may be an environment variable that you have to set to enable auto upgrade of your image.  There will be a wiki and instruction on how to make sure you have everything backup before doing any upgrade.

**Comment by noogen** [comment]
I've written up the vesta panel update script here: https://github.com/niiknow/vestacp/blob/master/rootfs/sysprepz/admin/bin/vesta-update.sh

I recently added php-fpm and is using it with my various docker build/changes.  This mean that I will also be testing it when Vesta v18 is released.  Simply ssh into the docker container and run:

```
sudo bash /bin/vesta-update.sh
```

Please review and feel free to report any bug or request any additional enhancement.  If there are no other issue, I will close this ticket in 48 hours.
