### ISSUE TITLE
Graph not generated

### ISSUE THREAD

**Issue by asrarak** [niiknow/vestacp#15]
Hi

I am using your image to deploy my vesta server. Other working great but not showing the image on the Graph section.

Thanks

**Comment by VikramRao** [comment]
Did you check your folder permissions. Check my screenshot. It works out of the box.
http://vikramrao.com/screenshot.jpg

**Comment by VikramRao** [comment]
Check my Screenshot. It works out of the box.

[](http://vikramrao.com/screenshot.jpg)

**Comment by VikramRao** [comment]
http://vikramrao.com/screenshot.jpg

**Comment by asrarak** [comment]
Hi Vikram,

Thank for the response, which folder nee dto check, in user folders or /usr/local/vesta/rrd/ ?
Running on latest docker-ce ubuntu 16.04

**Comment by VikramRao** [comment]
Use this shell script. It will handle everything for you. In case you are having trouble installing it on your current configured server, just add '-f' (without quotes) at the end of install command. Works perfectly.

**Comment by asrarak** [comment]
Wich script?

**Comment by VikramRao** [comment]
http://vestacp.com/pub/vst-install.sh

**Comment by noogen** [comment]
This issue is valid and related to the docker container.  Don't run VikramRao command as it's for Vesta installation.  Run this one instead:
```
sudo sed -i -e "s/if (\$dir_name/\/\/if (\$dir_name/g" /usr/local/vesta/web/list/rrd/image.php
```

This issue is result of my Docker redirecting the Vesta location; as a result, it no longer match the web document root.  Ref:  https://github.com/serghey-rodin/vesta/blob/master/web/list/rrd/image.php#L9

I will update the docker image shortly.

**Comment by asrarak** [comment]
Hi Noogen,

No, i am aware that the script for automatic fresh instalation.



> sudo sed -i -e "s/if (\$dir_name/\/\/if (\$dir_name/g" /usr/local/vesta/web/list/rrd/image.php


using that the graph was shown.
Thank you

**Comment by asrarak** [comment]
Also we may need a documentation to remove the unused package since every user have diffrent preference.
