### ISSUE TITLE
How do you overcome letsencrypt script problems?

### ISSUE THREAD

**Issue by hostmit** [niiknow/vestacp#2]
Hello! Would you advise, how do you manage letsencrypt script to be working? I'm facing:
Error: LetsEncrypt account registration 400
sed: can't read /usr/local/vesta/data/queue/letsencrypt.pipe: No such file or directory

**Comment by hostmit** [comment]
Touch'ing it doesnt help.
Error: LetsEncrypt account registration 400
with no futher logs

**Comment by noogen** [comment]
Sorry for the late response, I have been out the last week on Vacation in Japan.

Anyway, lets encrypt issue can be complicated to troubleshoot.  Maybe this will help:
1.  Check to make sure your DNS is correctly pointing to the *Domain* and the *Aliases* field values.
2.  Select IP Address 127.0.0.1 - don't worry, this is what you want to use with my docker image.  
3.  Uncheck *SSL Support* and save.
4.  Make sure you can hit the page with http://*Domain* and http://*Aliases*
5.  Now go back and check the *SSL Support*, then check *Lets Encrypt Support* and click save.

Additionally, host under new user and provide a valid email address.  Don't use admin.  If you use admin, please update the email address to something valid: https://forum.vestacp.com/viewtopic.php?f=11&t=14296

**Comment by noogen** [comment]
Closing old ticket with no response.
