### ISSUE TITLE
replaced with mysql

### ISSUE THREAD

**Issue by hi-noikiy** [niiknow/vestacp#23]
Hi.
is it can replaced with mysql 5.7.20?

**Comment by noogen** [comment]
It is 5.7 by default, but I prefer MariaDB so 10.1 was chosen for max compatibility.  If you want MySQL, then do your your fork and remove my mariadb sed.

**Comment by noogen** [comment]
I created 1.0.8-mysql tags: https://hub.docker.com/r/niiknow/vestacp/tags/

There's also a mysql branch.
