### ISSUE TITLE
Roundcube /webmail not accessible

### ISSUE THREAD

**Issue by zette** [niiknow/vestacp#3]
Hi,
I'm starting Your's image of VestaCP, and the panel at 8083 works with no problems.

But when i want to access RoundCube webmail at /webmail I get 404.

Any ideas?

**Comment by zette** [comment]
Found it. Apache conf had no link to roundcube:
/etc/apache2/conf.d# ln -s /etc/roundcube/apache.conf roundcube

^^ Fixed it.

**Comment by noogen** [comment]
It is disabled by default, for security purpose.  Just re-link the conf file.  I guess you found it.

Alternatively:
```
rsync -a /etc/apache2/conf-d/roundcube.conf /etc/apache2/conf.d
```
Note: all web confs that I disabled are recoverable from /etc/apache2/conf-d

**Comment by noogen** [comment]
Closing old ticket with no response.

**Comment by aolko** [comment]
still hot, debian 9 guide please
edit: fault in the 7.2 switcher template, how to fix?
