### ISSUE TITLE
Wrong Command with Volumes

### ISSUE THREAD

**Issue by LenKiMo** [niiknow/vestacp#4]
After running `mkdir -p /opt/vestacp/{vesta,home,backup}`, user made backup folder, but the next command it said:
`docker run -d --restart=always -p 2222:22 -p 80:80 -p 443:443 -p 3306:3306 -p 5432:5432 -p 8083:8083 -v /opt/vestacp/vesta:/vesta -v /opt/vestacp/home:/home -v /opt/vestacp/data:/backup niiknow/vestacp`

But user did not create `/opt/vestacp/data` before, so I think the `/opt/vestacp/data:/backup` should be `/opt/vestacp/backup:/backup`.

But even I change the command as `/opt/vestacp/backup:/backup`, Vesta still said there is not backup file but I am sure I put it right. Any idea about this?

**Comment by noogen** [comment]
Yes, it should be /opt/vestacp/backup.  I'll update the doc/README.   Did you successfully create the folders in /opt/vestacp/?

I'm just using /opt/vestacp as example.  You can store it in your home path, example: mkdir -p ~/vestadata/{vesta,home,backup} if you don't have access to /opt folder.  It's up to you.

Also, where are you getting the there's not a backup file message?  Are you trying to do restore?

**Comment by LenKiMo** [comment]
I tried to rebuild the image and container, then the problem is solved.
