### ISSUE TITLE
Postgresql shared buffer allocation

### ISSUE THREAD

**Issue by lazmo88** [niiknow/vestacp#47]
Heya, just FYI for anyone else who's trying to run this docker image on small VPS with less than 4Gb RAM, Postgresql shared buffer is set to 2GB which will make Postgresql to fail upon startup.

You can fix this by tweaking postgresql config file. 

As an idea, could it be possible to pass this setting as env variable to the docker container?

**Comment by noogen** [comment]
Sorry, it's actually the default behavior.  The standard PSQL reservation is 25% of the machine ram and I usually run our databases on 8GB Ram machine - https://github.com/niiknow/vestacp/blob/master/Dockerfile#L276

I'll add it to the readme somewhere.
