### ISSUE TITLE
VestaCP database password backup

### ISSUE THREAD

**Issue by theFra985** [niiknow/vestacp#50]
This is not an issue
I noticed that the maintainer has listed as a known issue the vesta bug that prevents from backing up the DB passwords correctly.
If it can help I have found this workaround on the vesta forum.
https://forum.vestacp.com/viewtopic.php?f=20&t=13239

**Comment by Skamasle** [comment]
This was fixed, but if you use mysql 5.7 maybe need reset all passwords or run script provided in you link to restore old password in users added before oficial patch for mysql 5.7
