### ISSUE TITLE
Unable to start /usr/local/vesta/nginx/sbin/vesta-nginx (Permission denied)

### ISSUE THREAD

**Issue by m4t7e0** [niiknow/vestacp#58]
Hi, i'm trying to start the vestacp service... the container (build from docker-compose) when start report this error:

start-stop-daemon: unable to start /usr/local/vesta/nginx/sbin/vesta-nginx (Permission denied)
i have tried also to run via command line 
root@9e4c06c027e8:/# /etc/init.d/vesta start
 * Starting vesta-nginx vesta-nginx start-stop-daemon: unable to start /usr/local/vesta/nginx/sbin/vesta-nginx (Permission denied)

the permission on file is : 
-rwxr-xr-x 1 root root 5806096 Jun 28 06:42 vesta-nginx
root@9e4c06c027e8:/usr/local/vesta/nginx/sbin#

**Comment by noogen** [comment]
I don't have an issue.  How are you creating and mounting your external volume?  I've seen permission issue when you use docker inside of home folder, example:  https://github.com/niiknow/vestacp/issues/38#issuecomment-366862234

I would suggest creating the folder as root:
```shell
total 20
drwxr-xr-x  5 root root 4096 Mar 13  2018 .
dr-xr-xr-x 25 root root 4096 Jul 11 20:14 ..
drwxr-xr-x  5 root root 4096 Jan 15  2018 aws
drwxr-xr-x  3 root root 4096 Mar 13  2018 redis
drwxr-xr-x  5 root root 4096 Feb 14  2018 vestacp
[ec2-user@xxx opt]$ cd vestacp/
[ec2-user@xxx vestacp]$ ls
backup  home  vesta
[ec2-user@xxx vestacp]$ ls -la
total 20
drwxr-xr-x 5 root root 4096 Feb 14  2018 .
drwxr-xr-x 5 root root 4096 Mar 13  2018 ..
drwxr-xr-x 3 root root 4096 Sep 24 05:10 backup
drwxr-xr-x 5 root root 4096 Apr 25 20:07 home
drwxr-xr-x 6 root root 4096 Feb 14  2018 vesta
[ec2-user@xxx vestacp]$ pwd
/opt/vestacp
```
My folder is under /opt/vestacp created as root.   You can run it as regular user as long as that user has permission to docker.  I run docker as ec2-user (not root) on AWS.

**Comment by noogen** [comment]
Stale issue with no response.
