### ISSUE TITLE
PHPMYADMIN Unaccessible

### ISSUE THREAD

**Issue by LenKiMo** [niiknow/vestacp#6]
Now by default, click `PHPMYADMIN` in the database tabs in VestaCP would take user to domain.com/phpmyadmin, but it weill return 404 error.
I wonder if it is not accessible by default? If it is, how to enable it?

**Comment by noogen** [comment]
For security reason, it is disabled by default.  This is similar to the Roundcube issue reported earlier.  To re-enable service, restore the configs from backup folder /etc/apache2/conf-d:

https://github.com/niiknow/vestacp/blob/master/Dockerfile#L361

```
rsync -a /etc/apache2/conf-d/phpmy*.conf /etc/apache2/conf.d
```

**Comment by LenKiMo** [comment]
Understood. I would have a try. Thank you.

**Comment by LenKiMo** [comment]
Sorry for bother again. 
After I run the commend, the page domain.com/phpmyadmin  is accessible but with 500 error.
I am not much familiar with Docker. Am I miss any predecessor work?

**Comment by noogen** [comment]
Have you try restarting apache?
```
service apache2 restart
```

**Comment by LenKiMo** [comment]
Yes I have tried. But it still.

**Comment by noogen** [comment]
Not sure what 500 issue is without details.  I just did it on my server and it works fine:  http://bart.noogen.net/phpmyadmin/

http://bart.noogen.net:8083
- use default admin login and pass

Would you have any kind of a log?  Does apache response correctly when you curl to the endpoint directly from inside of the docker shell?

```
curl http://localhost/phpmyadmin/
```

**Comment by LenKiMo** [comment]
Nothing.

If the target is `phpmyadmin` without slash it would says
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://localhost/phpmyadmin/">here</a>.</p>
</body></html>
```

But if the target is `http://localhost/phpmyadmin/` with slash, the curl return nothing.

The strange thing is there is not any error message in Apache's `error.log`.

And the problem is solved with this [post](https://stackoverflow.com/questions/21699774/internal-server-error-http-error-500-after-installing-phpmyadmin-on-a-certain) in Stackoverflow.
With this command then restart the Apache2:
```
sudo apt-get install php-mbstring php7.0-mbstring php-gettext
````
It seems like this would happen when user choose php7.0.

**Comment by noogen** [comment]
Sorry, it was the middle of the night.  I was trying to get you to hit Apache and I missed the port in my response.  It should be port 8080.

```
curl http://localhost:8080/phpmyadmin/
```

I guess you fixed it.   I'm not sure why this happen.  What version of my docker image are you using or are you building it yourself?  I'm pretty sure I have most of the package installed from the very beginning and have tested phpmyadmin.  This line in docker:  https://github.com/niiknow/vestacp/blob/master/Dockerfile#L61

php-gettext is not reference but it is usually a dep of many packages.  And the command below shows that it does exists on my docker:

```
ls -la /etc/php/7.0/mods-available/gettext.ini
```

**Comment by LenKiMo** [comment]
I am using the Docker image with `latest` tag, which seems like can't provide a specific version.
The `niiknow/docker-hostingbase` is 0.8.4.

Maybe I need to update the docker image without using `latest` tag.

And I understand the timezone problem, just reply me in the time you fell comfortable.

I would try to update the docker.
