### ISSUE TITLE
install ioncube loader

### ISSUE THREAD

**Issue by limogin** [niiknow/vestacp#71]
How I can install the ioncube loader?

**Comment by noogen** [comment]
https://www.digitalocean.com/community/tutorials/how-to-install-ioncube-on-ubuntu-16-04

**Comment by limogin** [comment]
Thanks for your attention,
My doubts is also related how to make the changes permanents inside the container when I instal the ioncube loader. Also, when I try to start a container there exists a default domain and ip that I'm unable to delete. I'm not sure how to proceed.

**Comment by noogen** [comment]
I add iconcube loader in 1.6.1
