### ISSUE TITLE
phpPgAdmin doesn't work properly

### ISSUE THREAD

**Issue by markolofsen** [niiknow/vestacp#75]
When I'm trying to list my databases through http://****/phppgadmin/ but is empty.
But my database really are created.

![phpPgAdmin 2019-04-08 12-50-50](https://user-images.githubusercontent.com/13606299/55718869-1545ba80-59fd-11e9-8b77-c285f96aca35.png)

**Comment by noogen** [comment]
@markolofsen it doesn't automatically log you in.  You have to login with your database user and password.  I know it's inconvenience but it's a security thing which prevent your DB from being publicly exposed if somehow it is accidentally available to the user.

![working](https://user-images.githubusercontent.com/95691/55762796-f3aef800-5a29-11e9-9579-0ba61860be29.png)

Click on the Servers->PostgreSQL tree view branch on the left to login.

**Comment by markolofsen** [comment]
@noogen Thanks, you was right!
