### ISSUE TITLE
Internal server error on php-fpm

### ISSUE THREAD

**Issue by akashbagchi26** [niiknow/vestacp#76]
Internal server error on php-fpm php7.2 when I restart the vps

**Comment by akashbagchi26** [comment]
There is no problem when i install the new site on php-fpm but when i reboot the vps getting 500 Internal Server Error on the site

**Comment by noogen** [comment]
I'm running php-fpm7.2 for a very long time with no issue.  When you get your internal server error, please check various logs for error details:
```shell
tail /var/log/php7.2-fpm.log
tail /var/log/nginx/error.log
tail /var/log/apache2/domains/your.domain.name.error.log
tail /var/log/apache2/error.log
```

Post any suspecting error if you need troubleshooting it.

**Comment by akashbagchi26** [comment]
*106 connect() to unix:/var/run/vesta-php-fpm-tekhgizmo.com.sock failed (2: No such file or directory) while connecting to upstream,

found this one on domain.name.error.log

**Comment by noogen** [comment]
php7.2-fpm service is not enabled on startup.  Add this line to the bottom of your startup file (/home/admin/bin/startup.sh): https://github.com/niiknow/vestacp/blob/master/rootfs/sysprepz/admin/bin/my-startup.sh#L18

```
./php7.2-fpm start
```

And then restart docker.

**Comment by akashbagchi26** [comment]
thanks, it worked

**Comment by patsotoe** [comment]
> 
> 
> php7.2-fpm service is not enabled on startup. Add this line to the bottom of your startup file (/home/admin/bin/startup.sh): https://github.com/niiknow/vestacp/blob/master/rootfs/sysprepz/admin/bin/my-startup.sh#L18
> 
> ```
> ./php7.2-fpm start
> ```
> 
> And then restart docker.

thanks this works awesome.
