### ISSUE TITLE
phpMyAdmin not work 

### ISSUE THREAD

**Issue by gamma05772** [niiknow/vestacp#88]
I has installed 1.8.1,but phpMyAdmin not work correctly ,show error  
"403
Forbidden
Unfortunately, you do not have permission to view this"

**Comment by noogen** [comment]
This is because I removed phpMyAdmin.  Replace it with new phpMyAdmin (adminer) nginx config, try:
```
sudo rsync -avh /vesta-start/etc/nginx/conf.d/*.inc /etc/nginx/conf.d/
sudo nginx -t
sudo nginx -s reload
```

Make sure nginx -t (test nginx config file) doesn't throw any error before you run -s reload.

**Comment by gamma05772** [comment]
thanks.
i try this below
###############################
[root@iZj6c2lvtw1kaa41257su4Z vestacp]# docker exec -it 45e0f240544d  /bin/bash
root@45e0f240544d:/# sudo rsync -avh /vestacp/etc/nginx/conf.d/*.inc /etc/nginx/conf.d/
sending incremental file list
rsync: change_dir "/vestacp/etc/nginx/conf.d" failed: No such file or directory (2)

sent 20 bytes  received 12 bytes  64.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]
root@45e0f240544d:/# ls /vestacp/etc/nginx/conf.d/
ls: cannot access '/vestacp/etc/nginx/conf.d/': No such file or directory
root@45e0f240544d:/# sudo rsync -avh /vesta/etc/nginx/conf.d/*.inc /etc/nginx/conf.d/
sending incremental file list

sent 80 bytes  received 12 bytes  184.00 bytes/sec
total size is 1.15K  speedup is 12.46
root@45e0f240544d:/# sudo nginx -t
nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /home/YL/conf/web/1gk.net.nginx.ssl.conf:4
nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /home/HB/conf/web/qzep.cn.nginx.ssl.conf:4
nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /home/CLnet/conf/web/cl1.net.nginx.ssl.conf:4
nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /home/HB/conf/web/hb1.net.nginx.ssl.conf:4
nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /home/CLcom/conf/web/cl5u.com.nginx.ssl.conf:4
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
root@45e0f240544d:/# sudo nginx -s reload
nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /home/YL/conf/web/1gk.net.nginx.ssl.conf:4
nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /home/HB/conf/web/qzep.cn.nginx.ssl.conf:4
nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /home/CLnet/conf/web/cl1.net.nginx.ssl.conf:4
nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /home/HB/conf/web/hb1.net.nginx.ssl.conf:4
nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /home/CLcom/conf/web/cl5u.com.nginx.ssl.conf:4
root@45e0f240544d:/# exit
exit
[root@iZj6c2lvtw1kaa41257su4Z vestacp]# reboot
###############################
but not fixed,show 404

404
Page Not Found
It seems that the page you were trying to reach does not exist anymore, or maybe it has just moved. You can start again from the home or go back to previous page.

Appreciate for any reply from you!

**Comment by noogen** [comment]
Ooopse, I forgot the main domain is proxy to apache and not fpm.  Try this, make sure you replace `{hostname}` with your actual panel hostname:

```
sudo bash /bin/vesta-update.sh
sudo echo 'include /etc/nginx/conf.d/dbadmin.inc;' /home/admin/web/{hostname}/private/dbadmin.conf
sudo nginx -t
sudo nginx -s reload
```

Explain:
`sudo bash /bin/vesta-update.sh` - Update your vesta with latest templates and php config

Then push the dbadmin config into your panel private/customizable nginx.conf

I'll work on the change to update the docker image.

**Comment by noogen** [comment]
Close as resolved with adminer.
